require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120
  IgnoredPatterns: ['\#.*'] # ignore long comments

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  ExcludedMethods:
    - describe

Metrics/ClassLength:
  Max: 500

Style/Documentation:
  Exclude:
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'db/migrate/*.rb'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

RSpec/NestedGroups:
  Max: 6
